export const ActionTypes = {
    REVERSE_SHOOTABLE:0,
    DRAG_START:1,
    SHOOTABLE_OVER_CELL:2,
    SHOOTABLE_LEAVE_CELL:3,
    DRAG_FINISH:4,
    JOIN_GAME:5,
    JOINVIEW_INITIALIZE:6,
    MOUSE_OVER_ENEMY:7,
    MAYBE_ATACK:8,
    ATACK:9,
    POLL_GAME_INFO:10,
    UPDATE_BATTLEFIELD_VIEW:11,
    INITIALIZE_BATTLEFIELD: 12,
    END_GAME: 13,
    MATCH_RESULT: 14,
    INITIALIZE_GAME_LIST:15
};